name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
#   boost-sast:
#     name: SAST
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: gosec
#         uses: boostsecurityio/boostsec-scanner-github@v4
#         with:
#           api_token: ${{ secrets.BOOST_API_KEY }}
#           registry_module: boostsecurityio/gosec
  boost-sast-dev:
    name: SAST (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: gosec
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/scanner-testing.git#gosec/fix-ruleid-mapping-and-update-docker
        with:
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/gosec
